/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Southern Fun", 4.1, "$");
        System.out.println(restaurant.toString());

        Review review1 = new Review("Awesome affordable food!", "Matt", 4);
        System.out.println(review1.toString());

        Review review2 = new Review("Superb customer service .", "Ann", 5);
        System.out.println(review2.toString());

        restaurant.addReview(review1);
        restaurant.addReview(review2);
        System.out.println(restaurant.toString());
    }
    public static void mainTwo(String[] args) {
        Shop shop = new Shop("Sports 4 Dayz", "All your sporting good needs", "$");
        System.out.println(shop.toString());

        Review review1 = new Review("Great prices!", "Dame", 5);
        System.out.println(review1.toString());

        Review review2 = new Review("My son loved the batting cages.", "Mary", 5);
        System.out.println(review2.toString());

        shop.addReview(review1);
        shop.addReview(review2);
        System.out.println(shop.toString());
    }
    public static void mainThree(String[] args) {
        Theater theater = new Theater("All You Can See", "movies", "$");
        System.out.println(theater.toString());

        Review review1 = new Review("They have reclining seats!", "Lucy", 5);
        System.out.println(review1.toString());

        Review review2 = new Review("Popcorn was cold.", "Amber", 2.5);
        System.out.println(review2.toString());

        theater.addReview(review1);
        theater.addReview(review2);
        System.out.println(theater.toString());
    }
}
