/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Southern Fun", 4.1, "$");
        System.out.println(restaurant.toString());

        Review review1 = new Review("Awesome affordable food!", "Matt", 4);
        System.out.println(review1.toString());

        Review review2 = new Review("Superb customer service .", "Ann", 5);
        System.out.println(review2.toString());

        restaurant.addReview(review1);
        restaurant.addReview(review2);
        System.out.println(restaurant.toString());
    }
}
